name: task_pragati
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/concrete-construction.png
    - assets/images/concstruction-site.png
    - assets/images/doha-construction.png
    - assets/images/profile_picture.png
    - assets/icons/navbar/home.svg
    - assets/icons/navbar/cash.svg
    - assets/icons/navbar/analytics.svg
    - assets/icons/navbar/progress.svg
    - assets/icons/navbar/material.svg
